/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpCheckbox {
    }
    interface IpCheckboxList {
        "item": string[];
    }
}
declare global {
    interface HTMLIpCheckboxElement extends Components.IpCheckbox, HTMLStencilElement {
    }
    var HTMLIpCheckboxElement: {
        prototype: HTMLIpCheckboxElement;
        new (): HTMLIpCheckboxElement;
    };
    interface HTMLIpCheckboxListElement extends Components.IpCheckboxList, HTMLStencilElement {
    }
    var HTMLIpCheckboxListElement: {
        prototype: HTMLIpCheckboxListElement;
        new (): HTMLIpCheckboxListElement;
    };
    interface HTMLElementTagNameMap {
        "ip-checkbox": HTMLIpCheckboxElement;
        "ip-checkbox-list": HTMLIpCheckboxListElement;
    }
}
declare namespace LocalJSX {
    interface IpCheckbox {
    }
    interface IpCheckboxList {
        "item"?: string[];
    }
    interface IntrinsicElements {
        "ip-checkbox": IpCheckbox;
        "ip-checkbox-list": IpCheckboxList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-checkbox": LocalJSX.IpCheckbox & JSXBase.HTMLAttributes<HTMLIpCheckboxElement>;
            "ip-checkbox-list": LocalJSX.IpCheckboxList & JSXBase.HTMLAttributes<HTMLIpCheckboxListElement>;
        }
    }
}
